/**
 * test/team-predictor.test.ts — Shadow team prediction tests
 *
 * Tests the Bayesian opponent team inference engine.
 * Key test: reveal 5 mons from real generated teams, verify the actual
 * 6th is in the predicted candidates list.
 */

import { expect } from 'chai';
import {
	createShadowTeam,
	revealMon,
	getSpeciesProbability,
	getTypeProbability,
	getTopCandidates,
	getThreats,
	getNotableAbsences,
	getShadowTeamSummary,
	formatShadowTeamSummary,
	applyBehavioralSignal,
	signalNoSwitch,
	inferMovePairs,
} from '../src/team-predictor';

// ─── Helpers ────────────────────────────────────────────────────

/** Real teams generated by PS for ground truth testing */
const REAL_TEAMS = [
	{
		mons: [
			{ id: 'camerupt', level: 91, ability: 'Solid Rock', moves: ['overheat', 'stealthrock', 'earthquake', 'willowisp'] },
			{ id: 'ironmoth', level: 78, ability: 'Quark Drive', moves: ['fireblast', 'uturn', 'sludgewave', 'morningsun'] },
			{ id: 'pawmot', level: 80, ability: 'Iron Fist', moves: ['closecombat', 'revivalblessing', 'doubleshock', 'icepunch'] },
			{ id: 'cetitan', level: 82, ability: 'Thick Fat', moves: ['iceshard', 'icespinner', 'earthquake', 'bellydrum'] },
			{ id: 'zangoose', level: 85, ability: 'Toxic Boost', moves: ['quickattack', 'swordsdance', 'knockoff', 'facade'] },
			{ id: 'kleavor', level: 78, ability: 'Sharpness', moves: ['xscissor', 'stoneaxe', 'defog', 'uturn'] },
		],
	},
	{
		mons: [
			{ id: 'dedenne', level: 88, ability: 'Cheek Pouch', moves: ['nuzzle', 'thunderbolt', 'dazzlinggleam', 'uturn'] },
			{ id: 'dialga', level: 73, ability: 'Pressure', moves: ['heavyslam', 'fireblast', 'dracometeor', 'dragontail'] },
			{ id: 'pelipper', level: 86, ability: 'Drizzle', moves: ['roost', 'hydropump', 'knockoff', 'hurricane'] },
			{ id: 'sandyshocks', level: 80, ability: 'Protosynthesis', moves: ['voltswitch', 'spikes', 'thunderbolt', 'earthpower'] },
			{ id: 'scrafty', level: 84, ability: 'Intimidate', moves: ['poisonjab', 'knockoff', 'drainpunch', 'dragondance'] },
			{ id: 'ironbundle', level: 78, ability: 'Quark Drive', moves: ['freezedry', 'encore', 'hydropump', 'icebeam'] },
		],
	},
	{
		mons: [
			{ id: 'hypno', level: 95, ability: 'Insomnia', moves: ['thunderwave', 'psychicnoise', 'knockoff', 'encore'] },
			{ id: 'amoonguss', level: 82, ability: 'Regenerator', moves: ['stompingtantrum', 'gigadrain', 'spore', 'sludgebomb'] },
			{ id: 'hitmonlee', level: 85, ability: 'Reckless', moves: ['highjumpkick', 'knockoff', 'poisonjab', 'stoneedge'] },
			{ id: 'primarina', level: 83, ability: 'Torrent', moves: ['sparklingaria', 'calmmind', 'drainingkiss', 'psychic'] },
			{ id: 'golemalola', level: 93, ability: 'Galvanize', moves: ['explosion', 'stoneedge', 'earthquake', 'doubleedge'] },
			{ id: 'slowking', level: 88, ability: 'Regenerator', moves: ['thunderwave', 'psyshock', 'slackoff', 'scald'] },
		],
	},
	{
		mons: [
			{ id: 'ariados', level: 95, ability: 'Swarm', moves: ['stickyweb', 'poisonjab', 'megahorn', 'toxicspikes'] },
			{ id: 'groudon', level: 72, ability: 'Drought', moves: ['precipiceblades', 'thunderwave', 'swordsdance', 'heatcrash'] },
			{ id: 'swampert', level: 83, ability: 'Torrent', moves: ['icebeam', 'earthquake', 'flipturn', 'yawn'] },
			{ id: 'talonflame', level: 83, ability: 'Gale Wings', moves: ['swordsdance', 'terablast', 'flareblitz', 'bravebird'] },
			{ id: 'kingdra', level: 84, ability: 'Sniper', moves: ['dragondance', 'outrage', 'ironhead', 'wavecrash'] },
			{ id: 'perrserker', level: 89, ability: 'Tough Claws', moves: ['stealthrock', 'ironhead', 'closecombat', 'uturn'] },
		],
	},
	{
		mons: [
			{ id: 'tentacruel', level: 84, ability: 'Liquid Ooze', moves: ['rapidspin', 'surf', 'sludgebomb', 'flipturn'] },
			{ id: 'magmortar', level: 88, ability: 'Flame Body', moves: ['scorchingsands', 'fireblast', 'knockoff', 'thunderbolt'] },
			{ id: 'arboliva', level: 91, ability: 'Seed Sower', moves: ['earthpower', 'energyball', 'hypervoice', 'strengthsap'] },
			{ id: 'crawdaunt', level: 84, ability: 'Adaptability', moves: ['knockoff', 'dragondance', 'aquajet', 'crabhammer'] },
			{ id: 'mesprit', level: 85, ability: 'Levitate', moves: ['knockoff', 'psychicnoise', 'thunderbolt', 'uturn'] },
			{ id: 'raikou', level: 81, ability: 'Pressure', moves: ['substitute', 'scald', 'thunderbolt', 'calmmind'] },
		],
	},
];

// ─── Tests ──────────────────────────────────────────────────────

describe('Team Predictor', () => {
	describe('Initialization', () => {
		it('should start with ~508 candidates', () => {
			const shadow = createShadowTeam();
			expect(shadow.candidates.size).to.be.closeTo(508, 5);
			expect(shadow.slotsRemaining).to.equal(6);
			expect(shadow.revealed.length).to.equal(0);
		});

		it('should have uniform weights initially', () => {
			const shadow = createShadowTeam();
			const weights = new Set<number>();
			for (const [, c] of shadow.candidates) {
				weights.add(c.weight);
			}
			expect(weights.size).to.equal(1); // all same weight
			expect(weights.has(1.0)).to.be.true;
		});
	});

	describe('Single reveal', () => {
		it('should move revealed mon from candidates to revealed list', () => {
			const shadow = createShadowTeam();
			const initialSize = shadow.candidates.size;
			revealMon(shadow, 'garchomp', 84, 'Rough Skin');

			expect(shadow.revealed.length).to.equal(1);
			expect(shadow.revealed[0].speciesId).to.equal('garchomp');
			expect(shadow.candidates.has('garchomp')).to.be.false;
			expect(shadow.candidates.size).to.be.lessThan(initialSize);
			expect(shadow.slotsRemaining).to.equal(5);
		});

		it('should update type counts', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'garchomp', 84); // Dragon/Ground

			expect(shadow.typeCount['Dragon']).to.equal(1);
			expect(shadow.typeCount['Ground']).to.equal(1);
		});

		it('should update weakness counts', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'garchomp', 84); // 4x weak to Ice, weak to Dragon/Fairy

			expect(shadow.weaknessCount['Ice']).to.equal(1);
			expect(shadow.weaknessCount['Dragon']).to.equal(1);
			expect(shadow.weaknessCount['Fairy']).to.equal(1);
			expect(shadow.doubleWeaknessCount['Ice']).to.equal(1);
		});

		it('should eliminate same base species via species clause', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'zoroarkhisui', 82); // Zoroark-Hisui

			// Regular Zoroark should be eliminated (same baseSpecies)
			expect(shadow.candidates.has('zoroark')).to.be.false;
		});
	});

	describe('Constraint elimination', () => {
		it('should eliminate species that would violate max 2 of same type', () => {
			const shadow = createShadowTeam();
			// Reveal 2 Water types
			revealMon(shadow, 'swampert', 83);   // Water/Ground
			revealMon(shadow, 'pelipper', 86);    // Water/Flying

			// Pure Water types should be eliminated (3rd Water would exceed limit)
			expect(shadow.candidates.has('vaporeon')).to.be.false;
			// Water/Ground also gone (species clause or Water limit)
			expect(shadow.candidates.has('quagsire')).to.be.false;
		});

		it('should eliminate species that would exceed weakness limit', () => {
			const shadow = createShadowTeam();
			// Reveal 3 mons weak to Ice
			revealMon(shadow, 'garchomp', 84);    // weak to Ice (4x)
			revealMon(shadow, 'dragonite', 75);    // weak to Ice (4x)
			revealMon(shadow, 'landorus', 79);     // weak to Ice (2x)

			// 4th Ice-weak mon should be eliminated
			// Salamence is Dragon/Flying = 4x Ice weak
			expect(shadow.candidates.has('salamence')).to.be.false;
		});

		it('should eliminate species that would exceed double-weakness limit', () => {
			const shadow = createShadowTeam();
			// Reveal 1 mon 4x weak to Ice
			revealMon(shadow, 'garchomp', 84);    // Dragon/Ground = 4x Ice

			// Another 4x Ice weak should be eliminated
			expect(shadow.candidates.has('landorustherian')).to.be.false;
		});

		it('should enforce incompatible pairs (Blissey/Chansey)', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'blissey', 100);

			expect(shadow.candidates.has('chansey')).to.be.false;
		});

		it('should enforce level-100 limit', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'blissey', 100);

			// All other level-100 mons should be eliminated
			for (const [, c] of shadow.candidates) {
				expect(c.level).to.not.equal(100);
			}
		});
	});

	describe('Move and set narrowing', () => {
		it('should narrow possible sets when moves are revealed', () => {
			const shadow = createShadowTeam();
			// Venusaur has multiple sets. Revealing specific moves should narrow.
			revealMon(shadow, 'venusaur', 84, 'Chlorophyll', ['sleeppowder', 'gigadrain']);

			const mon = shadow.revealed[0];
			// Should have fewer possible sets than total
			expect(mon.possibleSets.length).to.be.greaterThan(0);
			// All remaining sets should include both revealed moves
			for (const set of mon.possibleSets) {
				const poolIds = set.movepool.map(m => m.toLowerCase().replace(/[^a-z0-9]/g, ''));
				expect(poolIds).to.include('sleeppowder');
				expect(poolIds).to.include('gigadrain');
			}
		});

		it('should fully infer moveset for deterministic species', () => {
			const shadow = createShadowTeam();
			// Ninetales has 1 set with 4 moves: Fire Blast, Nasty Plot, Scorching Sands, Solar Beam
			revealMon(shadow, 'ninetales', 85, 'Drought', ['fireblast']);

			const mon = shadow.revealed[0];
			expect(mon.possibleSets.length).to.equal(1);
			expect(mon.inferredMoveset).to.not.be.null;
			expect(mon.inferredMoveset!.length).to.equal(4);
		});

		it('should update revealed mon on re-reveal with new moves', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'garchomp', 84, 'Rough Skin', ['earthquake']);
			revealMon(shadow, 'garchomp', 84, 'Rough Skin', ['earthquake', 'dragonclaw']);

			expect(shadow.revealed.length).to.equal(1); // not duplicated
			expect(shadow.revealed[0].knownMoves).to.include('earthquake');
			expect(shadow.revealed[0].knownMoves).to.include('dragonclaw');
		});
	});

	describe('MOVE_PAIRS inference', () => {
		it('should narrow sets when Rest is revealed (implies Sleep Talk)', () => {
			const shadow = createShadowTeam();
			// Find a species with rest+sleeptalk in a set
			revealMon(shadow, 'suicune', 79, '', ['rest']);
			inferMovePairs(shadow, 'suicune', 'rest');

			const mon = shadow.revealed[0];
			// After MOVE_PAIRS inference, remaining sets should include rest+sleeptalk
			if (mon.possibleSets.length > 0) {
				for (const set of mon.possibleSets) {
					const poolIds = set.movepool.map(m => m.toLowerCase().replace(/[^a-z0-9]/g, ''));
					// They should all have both rest and sleeptalk if pairs are enforced
					if (poolIds.includes('rest')) {
						expect(poolIds).to.include('sleeptalk');
					}
				}
			}
		});
	});

	describe('Behavioral inference', () => {
		it('should reduce weight of candidates matching filter', () => {
			const shadow = createShadowTeam();
			const initialWeight = shadow.totalWeight;

			// Discount all Water types
			applyBehavioralSignal(shadow, c => c.types.includes('Water'), 0.7);

			expect(shadow.totalWeight).to.be.lessThan(initialWeight);
			// Water types should have lower weight
			for (const [, c] of shadow.candidates) {
				if (c.types.includes('Water')) {
					expect(c.weight).to.be.closeTo(0.7, 0.001);
				} else {
					expect(c.weight).to.equal(1.0);
				}
			}
		});

		it('should compound with repeated signals', () => {
			const shadow = createShadowTeam();

			applyBehavioralSignal(shadow, c => c.types.includes('Water'), 0.7);
			applyBehavioralSignal(shadow, c => c.types.includes('Water'), 0.7);

			for (const [, c] of shadow.candidates) {
				if (c.types.includes('Water')) {
					expect(c.weight).to.be.closeTo(0.49, 0.01); // 0.7 * 0.7
				}
			}
		});

		it('signalNoSwitch should discount type-resists', () => {
			const shadow = createShadowTeam();
			const initialWeight = shadow.totalWeight;

			signalNoSwitch(shadow, 'Fire');

			// Water types (which resist Fire) should have reduced weight
			expect(shadow.totalWeight).to.be.lessThan(initialWeight);
		});
	});

	describe('Query functions', () => {
		it('getSpeciesProbability should return 0 for eliminated candidates', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'blissey', 100);

			expect(getSpeciesProbability(shadow, 'chansey')).to.equal(0);
			expect(getSpeciesProbability(shadow, 'blissey')).to.equal(0); // already revealed
		});

		it('getTypeProbability should return 1 for revealed types', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'garchomp', 84);

			expect(getTypeProbability(shadow, 'Dragon')).to.equal(1);
			expect(getTypeProbability(shadow, 'Ground')).to.equal(1);
		});

		it('getTopCandidates should return sorted by weight', () => {
			const shadow = createShadowTeam();
			const top = getTopCandidates(shadow, 5);

			expect(top.length).to.equal(5);
			for (let i = 1; i < top.length; i++) {
				expect(top[i].weight).to.be.at.most(top[i - 1].weight);
			}
		});

		it('getThreats should find SE threats against target', () => {
			const shadow = createShadowTeam();
			const threats = getThreats(shadow, ['Fire']);

			// Should find Water, Ground, Rock type threats
			const threatTypes = threats.map(t => t.reason);
			const hasWater = threatTypes.some(r => r.includes('Water'));
			const hasGround = threatTypes.some(r => r.includes('Ground'));
			expect(hasWater || hasGround).to.be.true;
		});
	});

	describe('Summary output', () => {
		it('should produce a formatted summary', () => {
			const shadow = createShadowTeam();
			revealMon(shadow, 'garchomp', 84, 'Rough Skin', ['earthquake']);
			revealMon(shadow, 'scizor', 78, 'Technician', ['bulletpunch']);

			const summary = getShadowTeamSummary(shadow);
			expect(summary.slotsRemaining).to.equal(4);
			expect(summary.topCandidates.length).to.be.greaterThan(0);

			const formatted = formatShadowTeamSummary(summary);
			expect(formatted).to.include('Shadow Team Intelligence');
			expect(formatted).to.include('4 slots unrevealed');
		});
	});

	// ─── CROWN JEWEL: 5-reveal predict 6th ──────────────────────

	describe('5-reveal predict 6th (ground truth validation)', () => {
		for (let teamIdx = 0; teamIdx < REAL_TEAMS.length; teamIdx++) {
			const team = REAL_TEAMS[teamIdx];
			const sixthMon = team.mons[5];

			it(`Team ${teamIdx + 1}: revealing 5 mons, 6th (${sixthMon.id}) should be in candidates`, () => {
				const shadow = createShadowTeam();

				// Reveal first 5 mons with full info
				for (let i = 0; i < 5; i++) {
					const mon = team.mons[i];
					revealMon(shadow, mon.id, mon.level, mon.ability, mon.moves);
				}

				// The actual 6th mon should still be in candidates
				const remaining = shadow.candidates;
				const sixthInCandidates = remaining.has(sixthMon.id);

				// Log useful info
				const candidateCount = remaining.size;
				const topCands = getTopCandidates(shadow, 10);

				console.log(`    Team ${teamIdx + 1}: ${candidateCount} candidates remain after 5 reveals`);
				console.log(`    Actual 6th: ${sixthMon.id} — ${sixthInCandidates ? 'FOUND' : 'MISSING'}`);
				if (candidateCount <= 30) {
					console.log(`    Candidates: ${Array.from(remaining.keys()).join(', ')}`);
				} else {
					console.log(`    Top 10: ${topCands.map(c => c.speciesId).join(', ')}`);
				}

				expect(sixthInCandidates).to.be.true;
			});

			it(`Team ${teamIdx + 1}: candidate pool should be significantly narrowed`, () => {
				const shadow = createShadowTeam();
				const initialSize = shadow.candidates.size;

				for (let i = 0; i < 5; i++) {
					const mon = team.mons[i];
					revealMon(shadow, mon.id, mon.level, mon.ability, mon.moves);
				}

				const remainingSize = shadow.candidates.size;
				const reduction = ((initialSize - remainingSize) / initialSize) * 100;

				console.log(`    Team ${teamIdx + 1}: ${initialSize} → ${remainingSize} candidates (${reduction.toFixed(1)}% reduction)`);

			// Should eliminate at least some candidates via constraints
			// (diverse teams may only eliminate ~5% via species clause alone)
			expect(remainingSize).to.be.lessThan(initialSize);
			});
		}

		it('should handle progressive reveals (1→2→3→4→5) with shrinking pool', () => {
			const team = REAL_TEAMS[0];
			const shadow = createShadowTeam();
			const sizes: number[] = [shadow.candidates.size];

			for (let i = 0; i < 5; i++) {
				const mon = team.mons[i];
				revealMon(shadow, mon.id, mon.level, mon.ability, mon.moves);
				sizes.push(shadow.candidates.size);
			}

			console.log(`    Progressive: ${sizes.join(' → ')}`);

			// Pool should monotonically decrease
			for (let i = 1; i < sizes.length; i++) {
				expect(sizes[i]).to.be.lessThan(sizes[i - 1]);
			}

			// 6th mon should be in final pool
			expect(shadow.candidates.has(team.mons[5].id)).to.be.true;
		});
	});

	// ─── Bulk validation with PS-generated teams ────────────────

	describe('Bulk generation validation', () => {
		it('should correctly predict 6th for 20 PS-generated teams', function () {
			this.timeout(30000);

			// eslint-disable-next-line @typescript-eslint/no-require-imports
			const { Teams } = require('../pokemon-showdown/dist/sim');
			// eslint-disable-next-line @typescript-eslint/no-require-imports
			const { Dex } = require('../pokemon-showdown/dist/sim');

			let successes = 0;
			let totalCandidates = 0;
			const failures: string[] = [];

			for (let t = 0; t < 20; t++) {
				const team = Teams.generate('gen9randombattle');
				const shadow = createShadowTeam();

				// Reveal first 5
				for (let i = 0; i < 5; i++) {
					const p = team[i];
					const sp = Dex.species.get(p.species);
					revealMon(shadow, sp.id, p.level, p.ability, p.moves);
				}

				const sixthSpecies = Dex.species.get(team[5].species).id;
				const found = shadow.candidates.has(sixthSpecies);

				if (found) {
					successes++;
				} else {
					failures.push(`Team ${t + 1}: ${sixthSpecies} not in ${shadow.candidates.size} candidates`);
				}
				totalCandidates += shadow.candidates.size;
			}

			const avgCandidates = totalCandidates / 20;
			console.log(`    Bulk: ${successes}/20 correct, avg ${avgCandidates.toFixed(0)} candidates remaining`);
			if (failures.length > 0) {
				console.log(`    Failures: ${failures.join('; ')}`);
			}

			// At least 90% should be correct (hard constraints should be accurate)
			expect(successes).to.be.at.least(18);
		});
	});
});
